# Generated by Django 3.0.5 on 2023-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop8', '0005_auto_20230320_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
